FROM python:3.11-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install gunicorn

COPY . .

EXPOSE 8000

CMD ["gunicorn", "student_management.wsgi:application", "--bind", "0.0.0.0:8000"]